### ISSUE TITLE
Glauth not starting with mysql-linux-arm64.so

### ISSUE THREAD

**Issue by hvsharma** [glauth/glauth#446]
root@neutronx-rpi:/serverapps/ldap/glauth# ./glauth-binary -c glauth-config.cfg
Mon, 02 Dec 2024 18:58:04 +0000 INF AP start
Mon, 02 Dec 2024 18:58:04 +0000 INF Web API enabled
Mon, 02 Dec 2024 18:58:04 +0000 INF Starting HTTP server address=0.0.0.0:5555
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xffff6eaa2868]

goroutine 1 [running]:
database/sql.(*Stmt).ExecContext(0x400012a090?, {0x2034ec0?, 0x29dc900?}, {0x0?, 0xffff6eaa8c90?, 0x400012a090?})
        database/sql/sql.go:2606 +0x38
database/sql.(*Stmt).Exec(...)
        database/sql/sql.go:2630
plugin/unnamed-79cae1023892539d5f496776160ef4a46fae6f00.MysqlBackend.CreateSchema({}, 0x2034ec0?)
        ./mysql.go:50 +0x64
github.com/glauth/glauth/v2/pkg/plugins.NewDatabaseHandler({0xffff6f028d80, 0x29dc900}, {0x4000128100, 0x7, 0x400046ce01?})
        github.com/glauth/glauth/v2/pkg/plugins/basesqlhandler.go:99 +0x4c8
plugin/unnamed-79cae1023892539d5f496776160ef4a46fae6f00.NewMySQLHandler({0x4000128100?, 0x400048a2a0?, 0x40002ee480?})
        ./mysql.go:17 +0x3c
github.com/glauth/glauth/v2/pkg/server.NewServer({0x400031fba8, 0x5, 0xf?})
        github.com/glauth/glauth/v2/pkg/server/server.go:149 +0x128c
main.startService()
        github.com/glauth/glauth/v2/glauth.go:156 +0x4ac
main.main()
        github.com/glauth/glauth/v2/glauth.go:108 +0x3d4

**Comment by hvsharma** [comment]
OS: Linux (Ubuntu Focal)
Glauth: 2.3.2

**Comment by hvsharma** [comment]
Arch: arm64 (Raspberry Pi 5)

**Comment by hvsharma** [comment]
I did. Please find the details below:

- MySQL DB Setup (v8.0.40):

```
create schema glauth_ldap collate utf8mb4_unicode_520_ci;

create user glauth_ldap
    identified by 'XXXXXX';

grant all privileges on glauth_ldap.* to glauth_ldap;
```

- Glauth Config:

```
[backend]
  datastore = "plugin"
  plugin="/serverapps/ldap/glauth/mysql-linux-arm64.so"
  pluginhandler="NewMySQLHandler"
  database="glauth_ldap:XXXXXX@tcp(localhost:3306)/glauth_ldap"

  # If you are using a client that requires reading the root DSE first
  # such as SSSD
  anonymousdse = false

  ## Configure dn format to use structures like
  ## "uid=serviceuser,cn=svcaccts,$BASEDN" instead of "cn=serviceuser,ou=svcaccts,$BASEDN"
  ## to help ease migrations from other LDAP systems
  # nameformat = "uid"
  # groupformat = "cn"

  ## Configure ssh-key attribute name, default is 'sshPublicKey'
  # sshkeyattr = "ipaSshPubKey"

```

<img width="385" alt="image" src="https://github.com/user-attachments/assets/18bc82ad-192e-4775-9703-ebf845dc1e68">

**Comment by Fusion** [comment]
I just tried it and it works for me. Here is to typically bootstrap glauth with mysql (in my case I used mariadb):

1. Create database and grant privileges, as you did
2. Start glauth with the config file you have here -> this creates the tables in the database
3. Stop glauth
4. Insert values in the database as per https://glauth.github.io/docs/databases.html
5. Start glauth

In step 1, I used somewhat different commands, but they should get you to the same place:

```
create database glauth;
grant all on glauth.* to glauth@localhost identified by 'glauth';
```

I would say that my configuration file is very similar to yours.

I do not quite understand why Go's built-in library would crash on acquiring a mutex:
![image](https://github.com/user-attachments/assets/1b6a9389-7081-4e13-9ebb-66abd9413078)

The stacktrace shows that S is not null, but perhaps it's a wrong structure type. No idea what would cause a corruption and it's even more difficult since I cannot reproduce it.

**Comment by Fusion** [comment]
Closing for inactivity.
